version: '3.8'
services:
  redis:
    image: redis:alpine
    restart: always
    environment:
      - REDIS_PASSWORD=root
#    ports:
#      - "3307:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"